/*
 * ConnectBot: simple, powerful, open-source SSH client for Android
 * Copyright 2007 Kenny Root, Jeffrey Sharkey
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.connectbot.service.terminal;

/**
 * Context for input operations to enable source-aware processing.
 * Allows different handling based on input source (keyboard, gesture, programmatic, etc.)
 */
public class InputContext {
    
    /**
     * Input source types
     */
    public enum InputSource {
        USER_KEYBOARD,    // Physical or soft keyboard input
        USER_GESTURE,     // Touch gestures (swipes, taps)
        PROGRAMMATIC,     // Generated by application code
        ACCESSIBILITY,    // Screen reader or accessibility service
        EXTERNAL_APP,     // Input from other applications
        PASTE_OPERATION,  // Clipboard paste
        MACRO_PLAYBACK    // Recorded macro playback
    }
    
    /**
     * Input priority levels
     */
    public enum Priority {
        LOW,      // Background operations, logging
        NORMAL,   // Regular user input
        HIGH,     // Important operations
        CRITICAL  // System or emergency operations
    }
    
    private final InputSource source;
    private final Priority priority;
    private final boolean preserveScrollPosition;
    private final boolean skipEcho;
    private final boolean skipBuffering;
    private final boolean bypassFilters;
    private final long timestamp;
    private final String description;
    
    /**
     * Private constructor - use Builder
     */
    private InputContext(Builder builder) {
        this.source = builder.source;
        this.priority = builder.priority;
        this.preserveScrollPosition = builder.preserveScrollPosition;
        this.skipEcho = builder.skipEcho;
        this.skipBuffering = builder.skipBuffering;
        this.bypassFilters = builder.bypassFilters;
        this.timestamp = System.currentTimeMillis();
        this.description = builder.description;
    }
    
    // Getters
    public InputSource getSource() { return source; }
    public Priority getPriority() { return priority; }
    public boolean shouldPreserveScrollPosition() { return preserveScrollPosition; }
    public boolean shouldSkipEcho() { return skipEcho; }
    public boolean shouldSkipBuffering() { return skipBuffering; }
    public boolean shouldBypassFilters() { return bypassFilters; }
    public long getTimestamp() { return timestamp; }
    public String getDescription() { return description; }
    
    /**
     * Check if this is user-initiated input
     */
    public boolean isUserInitiated() {
        return source == InputSource.USER_KEYBOARD || 
               source == InputSource.USER_GESTURE ||
               source == InputSource.PASTE_OPERATION;
    }
    
    /**
     * Check if this is automated input
     */
    public boolean isAutomated() {
        return source == InputSource.PROGRAMMATIC ||
               source == InputSource.MACRO_PLAYBACK;
    }
    
    /**
     * Check if this should trigger scroll reset
     */
    public boolean shouldTriggerScrollReset() {
        return !preserveScrollPosition && 
               (source == InputSource.USER_KEYBOARD || 
                source == InputSource.PASTE_OPERATION);
    }
    
    /**
     * Builder pattern for flexible context creation
     */
    public static class Builder {
        private InputSource source = InputSource.USER_KEYBOARD;
        private Priority priority = Priority.NORMAL;
        private boolean preserveScrollPosition = false;
        private boolean skipEcho = false;
        private boolean skipBuffering = false;
        private boolean bypassFilters = false;
        private String description = "";
        
        public Builder withSource(InputSource source) {
            this.source = source;
            return this;
        }
        
        public Builder withPriority(Priority priority) {
            this.priority = priority;
            return this;
        }
        
        public Builder preserveScrollPosition(boolean preserve) {
            this.preserveScrollPosition = preserve;
            return this;
        }
        
        public Builder skipEcho(boolean skip) {
            this.skipEcho = skip;
            return this;
        }
        
        public Builder skipBuffering(boolean skip) {
            this.skipBuffering = skip;
            return this;
        }
        
        public Builder bypassFilters(boolean bypass) {
            this.bypassFilters = bypass;
            return this;
        }
        
        public Builder withDescription(String description) {
            this.description = description != null ? description : "";
            return this;
        }
        
        public InputContext build() {
            return new InputContext(this);
        }
    }
    
    // Predefined contexts for common scenarios
    
    /**
     * Standard keyboard input
     */
    public static final InputContext DEFAULT_KEYBOARD = new Builder()
        .withSource(InputSource.USER_KEYBOARD)
        .withDescription("Default keyboard input")
        .build();
    
    /**
     * Arrow key gesture input
     */
    public static final InputContext GESTURE_ARROW = new Builder()
        .withSource(InputSource.USER_GESTURE)
        .preserveScrollPosition(true)
        .withDescription("Arrow key gesture")
        .build();
    
    /**
     * Page up/down gesture input
     */
    public static final InputContext GESTURE_PAGE = new Builder()
        .withSource(InputSource.USER_GESTURE)
        .preserveScrollPosition(true)
        .skipBuffering(true)
        .withDescription("Page up/down gesture")
        .build();
    
    /**
     * Clipboard paste operation
     */
    public static final InputContext PASTE = new Builder()
        .withSource(InputSource.PASTE_OPERATION)
        .withPriority(Priority.HIGH)
        .withDescription("Clipboard paste")
        .build();
    
    /**
     * Programmatic key generation
     */
    public static final InputContext PROGRAMMATIC_KEY = new Builder()
        .withSource(InputSource.PROGRAMMATIC)
        .preserveScrollPosition(true)
        .skipEcho(true)
        .withDescription("Programmatic key input")
        .build();
    
    /**
     * Accessibility input
     */
    public static final InputContext ACCESSIBILITY = new Builder()
        .withSource(InputSource.ACCESSIBILITY)
        .withPriority(Priority.HIGH)
        .withDescription("Accessibility service input")
        .build();
    
    /**
     * Emergency/system input
     */
    public static final InputContext SYSTEM_EMERGENCY = new Builder()
        .withSource(InputSource.PROGRAMMATIC)
        .withPriority(Priority.CRITICAL)
        .bypassFilters(true)
        .withDescription("System emergency input")
        .build();
    
    /**
     * Factory methods for common contexts with customization
     */
    
    public static InputContext gestureInput(String gestureType) {
        return new Builder()
            .withSource(InputSource.USER_GESTURE)
            .preserveScrollPosition(true)
            .withDescription("Gesture: " + gestureType)
            .build();
    }
    
    public static InputContext programmaticInput(String operation) {
        return new Builder()
            .withSource(InputSource.PROGRAMMATIC)
            .preserveScrollPosition(true)
            .skipEcho(true)
            .withDescription("Programmatic: " + operation)
            .build();
    }
    
    public static InputContext keyboardInput(boolean preserveScroll) {
        return new Builder()
            .withSource(InputSource.USER_KEYBOARD)
            .preserveScrollPosition(preserveScroll)
            .withDescription("Keyboard input")
            .build();
    }
    
    @Override
    public String toString() {
        return String.format("InputContext{source=%s, priority=%s, preserveScroll=%s, " +
                           "skipEcho=%s, skipBuffer=%s, bypass=%s, desc='%s'}",
                           source, priority, preserveScrollPosition, skipEcho, 
                           skipBuffering, bypassFilters, description);
    }
    
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        
        InputContext that = (InputContext) obj;
        return source == that.source &&
               priority == that.priority &&
               preserveScrollPosition == that.preserveScrollPosition &&
               skipEcho == that.skipEcho &&
               skipBuffering == that.skipBuffering &&
               bypassFilters == that.bypassFilters &&
               description.equals(that.description);
    }
    
    @Override
    public int hashCode() {
        int result = source.hashCode();
        result = 31 * result + priority.hashCode();
        result = 31 * result + (preserveScrollPosition ? 1 : 0);
        result = 31 * result + (skipEcho ? 1 : 0);
        result = 31 * result + (skipBuffering ? 1 : 0);
        result = 31 * result + (bypassFilters ? 1 : 0);
        result = 31 * result + description.hashCode();
        return result;
    }
}